Upgrade client-go (#104)
* Switched to go modules and updated client-go.

* Regenerated the Shipper client using the new code-generator package

* Changed the hack/update-codegen.sh script to use the new generator
using go modules

* Added the methods to the workqueue metric provider so that it meets
the new client-go interface requirements.

* ci: remove dep artifacts

Now that we have moved to Go Modules, we no longer need to keep Gopkg
files (dependencies are now managed by go.mod and go.sum), nor do we
need to install and call `dep` in our CI pipeline. Instead, now we just
call `go mod verify`, and ensure that all go commands use the vendored
version of libraries by specifying `-mod=vendor`.

* ci: upgrade golang to 1.12

We can't really use modules in 1.10. Also, we have successfully ran
shipper built with 1.12, so that's the reasonable thing to do.

* ci: skip hack when linting/testing/building shipper

Since hack/tools.go got introduced, trying to build /hack/ fails with:

	hack/tools.go:4:8:error: build constraints exclude all Go files
	in vendor/k8s.io/code-generator

We could just add a build tag to make it compile, but there's not much
of a gain there, so let's just skip it completely instead.

* ci: cut down on the amount of stuff we download

1. The kubernetes was only needed because of an older version of
k8s.io/code-generator. Now that it's been upgraded, it's no longer
needed.

2. kubectl is not needed since microk8s already installs a version of
that. For convenience, we alias `kubectl` to `microk8s.kubectl`

* Started refactoring the controllers and unit tests to use the new client-go.

* tests: finish refactoring for upgraded client-go

client-go's fake dynamic client no longer contains actions from the
non-dynamic client, so we had to split up, and sometimes join, lists of
actions so they could be checked properly.

With this, now all the unit tests pass with new client-go \o/

* Cleanup dead code and out of date comments