ci: skip hack when linting/testing/building shipper
Since hack/tools.go got introduced, trying to build /hack/ fails with:

	hack/tools.go:4:8:error: build constraints exclude all Go files
	in vendor/k8s.io/code-generator

We could just add a build tag to make it compile, but there's not much
of a gain there, so let's just skip it completely instead.