types: use the same GroupName everywhere
In previous versions the groupName listed in apis/shipper/register.go
was different from the "group" in apis/shipper/v1/doc.go. As a result,
the generated Fake clients for tests had an incorrect GroupVersionKind
attached to them, which caused tests to fail.

The tests would fail in two ways. First, the clientset would return
"NotFound" for objects that had been added to the fixture:

    --- FAIL: TestPendingToShipping (0.00s)
        shipmentorder_controller_test.go:98: error syncing
        ShipmentOrder: transition ShipmentOrder "default/ship-it" to
        "Shipping": shipmentorders.shipper "ship-it" not found

Second, we would see the following log message:

    E0209 16:08:28.717180   71218 reflector.go:205]
    github.com/bookingcom/shipper/pkg/client/informers/externalversions/factory.go:74:
    Failed to list *v1.ShipmentOrder: no kind "ShipmentOrderList" is
    registered for version "shipper/v1"

This is confusing, since  pkg/apis/shipper/v1/register.go clearly lists
'ShipmentOrderList' in addKnownTypes().

Both of these were due to the mismatch between the GroupVersionKind
of a newly-created &shipperv1.ShipmentOrder{}
(stable.shipper/v1) and the GVK that fake clients were working with
(shipper/v1).

This commit homegenizes the Group name to 'shipper.booking.com' in all
places (register.go, doc.go, docs, example CRDs), and regenerates the
client code to match.